trigger:
  branches:
    include:
    - '*'
pr:
  branches:
     include:
     - '*'

# Define machines on which the build will run.
jobs:
- job: macOS
  timeoutInMinutes: 360
  displayName: OSX-10.14
  pool:
    vmImage: macOS-10.14
  strategy:
    matrix:
      Plain:
        CMakeArgs-mlpack: '-DDEBUG=ON -DPROFILE=OFF -DBUILD_PYTHON_BINDINGS=OFF'
        CMakeArgs-models: '-DDEBUG=ON'

  steps:
  - template: macos-steps.yaml

